app:
  storage:
    type: 'local'
    local:
      save_path: './storage/avatars'

  # Development режим с in-memory кешированием
  cache:
    type: 'memory'
    warn_memory_level: 70
    ttl:
      avatars: 1800 # 30 минут для development
      metadata: 300 # 5 минут для development
      lists: 60 # 1 минута для development
      exists: 60 # 1 минута для development
    memory:
      max_items: 500
      max_memory: 50

  server:
    host: '0.0.0.0'
    port: 3000

  database:
    driver: 'postgresql'
    connection:
      maxRetries: 3
      retryDelay: 2000
    network:
      host: 'postgres'
      port: 5432
      database: 'avatar_gen'
      username: 'postgres'
      password: 'password'
      ssl: false

  logging:
    level: 'debug'
    verbose: true
    pretty: true
